package org.eclipse.scout.apps.testipa.testipa.shared.abstractobject.field;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "org.eclipse.scout.apps.testipa.testipa.client.abstractobject.field.AbstractPasswordField", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AbstractPasswordFieldData extends AbstractValueFieldData<String> {
	private static final long serialVersionUID = 1L;
}
